### ISSUE TITLE
Skeleton loading state is broken

### ISSUE THREAD

**Issue by huayunh** [pxblue/angular-design-patterns#102]
#### Describe the bug

Skeleton GG

#### What is the expected behavior?

No RSOD

#### What are the steps to reproduce?
1. Go to https://stackblitz.com/github/pxblue/angular-design-patterns 
2. Go to skeleton

#### Screenshots or links to minimum reproduction example

![image](https://user-images.githubusercontent.com/8997218/124656326-0ade2980-de6f-11eb-8fa8-d84c474f0b45.png)

#### Environment
Stackblitz, Chrome, Mac

**Comment by joebochill** [comment]
We should check to see if this is just a stackblitz issue or if it's a local issue as well...

The showcase demo seems to be loading successfully in Stackblitz...maybe we just need to move the icon setup to the app component instead of having it in the skeleton component.

**Comment by ektasawant** [comment]
This issue has been fixed in https://github.com/pxblue/angular-design-patterns/pull/110
![image](https://user-images.githubusercontent.com/10433274/129936035-aec9ce0d-60d6-48f0-9427-5835d2c79a07.png)
