### ISSUE TITLE
Highlight user entered value if input is invalid

### ISSUE THREAD

**Issue by ektasawant** [pxblue/angular-design-patterns#119]
#### Describe the bug
1. Go to URL /forms-and-validation/fixed-length-passcode
2. Enter invalid passcode `111111`.
3. It gives error `invalid passcode`.

#### What is the expected behavior?
 1. The field should active again
 2. Select / highlight the entire user-entered passcode.
![image](https://user-images.githubusercontent.com/10433274/131465388-33f723cf-bdfa-47a5-aef2-327363320b32.png)

#### What are the steps to reproduce?
1. Go to /forms-and-validation/fixed-length-passcode
2. Enter invalid passcode

Note: Same behavior should apply for `Verify on submit` code example URL - `/forms-and-validation/verify-on-submit`

**Comment by jeffvg** [comment]
lets look in to this and check angular themes for highlight color

**Comment by huayunh** [comment]
I am going to take a stab at changing ng theme
