### ISSUE TITLE
Update password validation example to remove title on small view

### ISSUE THREAD

**Issue by jeffvg** [pxblue/angular-design-patterns#129]
#### Describe the bug
Currently the page title is displayed when viewing example on small view
#### What is the expected behavior?
Title should be hidden
#### What are the steps to reproduce?
1. Go to...
2. Click on...

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/37150565/132887208-273384f2-083b-4961-b288-12b750c440bb.png)

**Comment by ektasawant** [comment]
Couldn't find this issue in NG design pattern.
