### ISSUE TITLE
Required field error triggers on click events and blur

### ISSUE THREAD

**Issue by jeffvg** [pxblue/angular-design-patterns#130]
#### Describe the bug
Currently all required fields trigger field error on click event and on focus/blur. Per design this should only trigger when the submit button has been called
#### What is the expected behavior?
Clicking through the fields or tabbing through the fields should not trigger any fields required until submit has been clicked
#### What are the steps to reproduce?
1. Go to...http://localhost:4200/forms-and-validation/sectioned-form
2. Click through all the required fields
3. refresh
4. tab through all the required fields

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/37150565/132891794-40c89cdf-caa1-4877-900f-5cb554f9287c.png)

**Comment by emclaug2** [comment]
This is going to be the preferred behavior, show a 'required' error on blur.  The react-design-patterns need to be updated to match this behavior.
