### ISSUE TITLE
Mobile view breaking for table form

### ISSUE THREAD

**Issue by ektasawant** [pxblue/angular-design-patterns#155]
#### Describe the bug
Mobile view is breaking for table form design pattern.
![bug](https://user-images.githubusercontent.com/10433274/139022368-518f51a1-8692-48af-8785-86ad283c1211.PNG)

#### What is the expected behavior?
In mobile it should show below UI
![image](https://user-images.githubusercontent.com/10433274/139022270-d980b3dd-7d77-4e11-a760-5533ffe4accf.png)

#### What are the steps to reproduce?
1. Go to http://localhost:4200/forms-and-validation/in-a-table
2. Check mobile view
		
#### Anything else to add?
Need to check breakpoint
https://github.com/pxblue/angular-design-patterns/blob/d6612ed94cd1edfea697a58d7b119cd4879e9192/src/app/pages/forms-and-validation/in-a-table/in-a-table.component.ts#L46

**Comment by emclaug2** [comment]
599.98px should be 600px.
