### ISSUE TITLE
Bottom sheet covers entire screen on landscape view

### ISSUE THREAD

**Issue by daileytj** [pxblue/angular-design-patterns#30]
#### Bug or feature request?
Enhancement
#### What is the expected behavior?
Bottom sheet to include sticky close button/link
#### What is the current behavior?
Bottom sheet currently covers entire screen on landscape view, user will need to scroll to touch/click close button
#### What are the steps to reproduce?
1.  Open complex bottom sheet on any device or simulate in browser then open bottom sheet

#### What is your environment?

 Framework
- [X] Angular

 Browser
- [ ] Internet Explorer
- [ ] Safari
- [X] Chrome
- [ ] Firefox

 Operating System
- [ ] MacOS
- [ ] Windows
- [ ] Other

**Comment by emclaug2** [comment]
<img width="642" alt="Screen Shot 2020-08-19 at 9 24 49 AM" src="https://user-images.githubusercontent.com/6538289/90640407-ee58e480-e1fd-11ea-8b5a-aa6d9536355b.png">

The close button should be positioned at the bottom of the screen, at all times.

**Comment by emclaug2** [comment]
Check the react complex bottom sheet example as well.
