### ISSUE TITLE
Should run on IE 11

### ISSUE THREAD

**Issue by jeffvg** [pxblue/angular-design-patterns#33]
#### Describe the bug
Missing styles throughout all of the examples.
Missing icons
i18n pattern controlling entire app.
etc...
 
#### What is the expected behavior?
patterns and app to work with IE

#### What are the steps to reproduce?
1. Run repo
2. Open in IE
#### Environment
Windows
IE 11

**Comment by emclaug2** [comment]
The design patterns repo now works in IE11, but it's not very pretty.

**Comment by huayunh** [comment]
IE11 will no longer be supported after May 2021; will need to make stories to update support for IE11.
