### ISSUE TITLE
Code needs linting

### ISSUE THREAD

**Issue by huayunh** [pxblue/angular-design-patterns#4]
#### Describe the desired behavior
Code needs to be linted (after #3 is merged)
Remember to umcomment in the circle ci file

#### Describe the current behavior
It has nearly 300 problems

#### Is this request related to a current issue?
NO

**Comment by joebochill** [comment]
Also, make sure to go through and check/remove any instances of the eslint-disable comments

**Comment by emclaug2** [comment]
The code is already linted and enforced using circleci.  There is one line that is disabling eslint on a enum.  I've opened a PR here to update our eslint rules to allow for enumMembers to use the UPPER_CASE naming convention.

https://github.com/pxblue/code-standards/pull/27
