### ISSUE TITLE
Bottomsheet not displaying

### ISSUE THREAD

**Issue by huayunh** [pxblue/angular-design-patterns#45]
#### Describe the bug

Bottomsheet not displaying (at least not on Stackblitz)

This holds for both Basic bottomsheet and complex bottomsheet

#### What is the expected behavior?

Should display

#### What are the steps to reproduce?
1. Go to https://stackblitz.com/github/pxblue/angular-design-patterns?file=src%2Fapp%2Fpages%2Foverlays%2Fbasic-bottom-sheet%2Fbasic-bottom-sheet.component.ts
2. Click on the three dots icon on the top
3. Observe that no bottomsheet shows up
4. See the console

#### Screenshots or links to minimum reproduction example

Apparently there is an overlay, but with no sheets
![image](https://user-images.githubusercontent.com/8997218/90172501-1a451780-dd71-11ea-90b8-a79ccd8cae72.png)

Here is the console

![image](https://user-images.githubusercontent.com/8997218/90172642-51b3c400-dd71-11ea-99d4-e71d38e955c1.png)

#### Environment

Angular Stackblitz Chrome Mac
		
#### Anything else to add?
> "Should just need to add the bottomsheet to the entrycomponents array in the module.ts file"

**Comment by daileytj** [comment]
I made a branch that fixes the stackblitz problem, but it breaks locally and the complex bottomsheet styles are broken on stackblitz.

https://stackblitz.com/github/pxblue/angular-design-patterns/tree/bug/bottomsheet-not-displaying?file=src%2Fapp%2Fpages%2Foverlays%2Fcomplex-bottom-sheet%2Fcomplex-bottom-sheet.module.ts

**Comment by daileytj** [comment]
Updated to fix complex bottom sheet styles. https://stackblitz.com/github/pxblue/angular-design-patterns/tree/bug/bottomsheet-not-displaying
