### ISSUE TITLE
Multiselect List's "Snackbar" behaves in a funny way

### ISSUE THREAD

**Issue by huayunh** [pxblue/angular-design-patterns#49]
#### Describe the bug

The bottomsheet / snack bar thing slides-in in a weird way.

#### What is the expected behavior?

Either replace it with a real snackbar, or have it slide in from the bottom

#### What are the steps to reproduce?
1. go to multi select list
2. Click on any item

#### Screenshots or links to minimum reproduction example

![ezgif-7-ab006aa934bf](https://user-images.githubusercontent.com/8997218/90911100-7548c100-e3a6-11ea-9767-7c694d32f7a6.gif)

#### Environment
localhost, chrome

**Comment by joebochill** [comment]
This one is a little tricky...the angular snackbar only supports a single action button. That's why we wrote our own for this. But I agree the animation looks odd.

**Comment by joebochill** [comment]
Might be able to do this with a service?
