### ISSUE TITLE
Icons not aligned properly

### ISSUE THREAD

**Issue by daileytj** [pxblue/angular-design-patterns#66]
#### Describe the desired behavior
Icons should be properly aligned in all design patterns

#### Describe the current behavior
Icons are not properly aligned in the following design patterns:
- Action list
- Multiselect list
- Sortable list
- Internationalization

**Comment by joebochill** [comment]
@daileytj can you take another look at this and add some more details (screenshots?) for which icons are not aligned

**Comment by daileytj** [comment]
![Screen Shot 2020-11-04 at 2 09 34 PM](https://user-images.githubusercontent.com/13989985/98157488-6c489580-1ea7-11eb-8abc-f2af81d2b221.png)
![Screen Shot 2020-11-04 at 2 09 16 PM](https://user-images.githubusercontent.com/13989985/98157489-6ce12c00-1ea7-11eb-8fac-5cfa24ce4456.png)
![Screen Shot 2020-11-04 at 2 08 23 PM](https://user-images.githubusercontent.com/13989985/98157490-6ce12c00-1ea7-11eb-97c4-29d520568263.png)
![Screen Shot 2020-11-04 at 2 08 46 PM](https://user-images.githubusercontent.com/13989985/98157491-6ce12c00-1ea7-11eb-917e-615ef70232b9.png)

**Comment by joebochill** [comment]
We'll need to look into this and see if it's an issue with the styles in the ILI or if we have styles in the design-pattern-monorepo that are breaking the alignment. We might also need to update the version of the component library we are using to make sure we have the latest.
