### ISSUE TITLE
Collapsible Appbar Transition

### ISSUE THREAD

**Issue by emclaug2** [pxblue/angular-design-patterns#76]
#### Describe the desired behavior
Since our ionic examples are basically angular code, can we update this angular example to have a smooth transition like this?
https://stackblitz.com/github/pxblue/collapsible-appbar/tree/ionic

#### Describe the current behavior
The secondary toolbar just appears instead of performing a transition. 

#### Is this request related to a current issue?
No

**Comment by jeffvg** [comment]
PXBLUE-1593 story will enhance this.
