### ISSUE TITLE
Drawer Padding is wrong

### ISSUE THREAD

**Issue by huayunh** [pxblue/angular-design-patterns#88]
#### Describe the bug

The left padding of the main navigation drawer in the design pattern monorepo is wrong. It should maintain a 16px padding when no icon is present. Right now it is 8px, as shown in the screenshot below.

#### What is the expected behavior?

Like what it does in the drawer storybook story.

#### What are the steps to reproduce?
1. Go to https://stackblitz.com/github/pxblue/angular-design-patterns?file=src%2Fapp%2Fpages%2Fapp-bar%2Fcollapsible-app-bar%2Fcollapsible-app-bar.component.ts 
2. Observe the drawer text is not aligned with the drawer header

#### Screenshots or links to minimum reproduction example

![image](https://user-images.githubusercontent.com/8997218/107158495-7e2f4e00-6958-11eb-8ff3-72228cd771e4.png)

#### Environment
MacOS chrome stackblitz

**Comment by emclaug2** [comment]
This is very weird; I'm trying this with updated dependencies but I cannot reproduce.  I've made a PR to update the lock file though.
